use_frameworks!

source 'https://github.com/GitWangKai/PriviteRepo.git'

platform :ios, '8.0'

target 'PHDemo_Example' do
  pod 'PHDemo', :path => '../'

  target 'PHDemo_Tests' do
    inherit! :search_paths

    
  end
end
